name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install @octokit/rest fs
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node update_readme.js
    - name: Commit and push if changed
      run: |
        git config --global user.email "yakirisk@gmail.com"
        git config --global user.name "lucaszebre"
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update README" && git push)